
import java.awt.Color;
import java.awt.Image;
import java.io.File;
import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.BorderFactory;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.border.Border;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author win
 */
public class Images_Window extends javax.swing.JFrame {
    PropertyType type = new PropertyType();
    HashMap<String, Integer> map = type.getTypesMap();
    String property_image_path = "";
    int propertyId = 0;
    
    


    /**
     * Creates new form Images_Window
     */
    public Images_Window() {
        initComponents();
        Border border = BorderFactory.createMatteBorder(0, 0, 3, 0, Color.white);
         ProTypeHeadPanel.setBorder(border);
         addCombo();
         ShowPropertiesTable();
         jTable1.setRowHeight(40);
         jTable1.setSelectionBackground(Color.red);
         jTable1.getColumnModel().getColumn(0).setPreferredWidth(10);
         jTable1.getColumnModel().getColumn(1).setPreferredWidth(240);
    }
     public void addCombo() {

        for (String s : map.keySet()) {
            jComboBox1.addItem(s);

        }
    }
      public void ShowPropertiesTable() {
        Property property = new Property();
        ArrayList<Property> list = property.PropertyList();
        //	Id. type square_feet ownerId price address bedrooms bathrooms age balcony pool backyard garage description
        //table columns
        String[] ColNames = {"ID", "Address"};
        Object[][] rows = new Object[list.size()][2];
        //add data form the list to the rows
        for (int i = 0; i < list.size(); i++) {
            rows[i][0] = list.get(i).getId();
            rows[i][1] = list.get(i).getAddress();
   
     

        }
        DefaultTableModel model = new DefaultTableModel(rows, ColNames);
        jTable1.setModel(model);
        

    }
       public void fillTypeList() {
        PropertyType type = new PropertyType();
        HashMap<byte[], Integer> imageList = new Property().PropertyImageList(propertyId);
        DefaultListModel listModel = new DefaultListModel();
        int i = 0;
        for (Integer id : imageList.values()) {
            listModel.add(i, id);
            i++;

        }
        jList1.setModel(listModel);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        ProTypeHeadPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Addbtn = new javax.swing.JButton();
        RomoveBtn = new javax.swing.JButton();
        SeeImage_btn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jLabel3 = new javax.swing.JLabel();
        jButton_Browse = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel_Image = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));

        ProTypeHeadPanel.setBackground(new java.awt.Color(102, 51, 0));

        jLabel1.setBackground(new java.awt.Color(153, 51, 0));
        jLabel1.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Property-Images");

        javax.swing.GroupLayout ProTypeHeadPanelLayout = new javax.swing.GroupLayout(ProTypeHeadPanel);
        ProTypeHeadPanel.setLayout(ProTypeHeadPanelLayout);
        ProTypeHeadPanelLayout.setHorizontalGroup(
            ProTypeHeadPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProTypeHeadPanelLayout.createSequentialGroup()
                .addGap(357, 357, 357)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ProTypeHeadPanelLayout.setVerticalGroup(
            ProTypeHeadPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProTypeHeadPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        Addbtn.setBackground(new java.awt.Color(0, 153, 51));
        Addbtn.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        Addbtn.setForeground(new java.awt.Color(0, 0, 0));
        Addbtn.setText("Add");
        Addbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddbtnActionPerformed(evt);
            }
        });

        RomoveBtn.setBackground(new java.awt.Color(255, 51, 51));
        RomoveBtn.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        RomoveBtn.setForeground(new java.awt.Color(0, 0, 0));
        RomoveBtn.setText("Remove");
        RomoveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RomoveBtnActionPerformed(evt);
            }
        });

        SeeImage_btn.setBackground(new java.awt.Color(0, 102, 204));
        SeeImage_btn.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        SeeImage_btn.setForeground(new java.awt.Color(0, 0, 0));
        SeeImage_btn.setText("See Images");
        SeeImage_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SeeImage_btnActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Selected Type:");

        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jTable1.setBackground(new java.awt.Color(204, 204, 204));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jList1.setBackground(new java.awt.Color(204, 204, 204));
        jList1.setForeground(new java.awt.Color(0, 0, 0));
        jList1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jList1);

        jLabel3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Select Images:");

        jButton_Browse.setBackground(new java.awt.Color(204, 204, 204));
        jButton_Browse.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton_Browse.setForeground(new java.awt.Color(0, 0, 0));
        jButton_Browse.setText("Browse");
        jButton_Browse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_BrowseActionPerformed(evt);
            }
        });

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("<html>This table contains the properties Id and address. Click button to show the image</html>");

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("<html>This list contains the image id of the selected property(for more select property) from the table</html>");

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("<html>Select the item from the list to display or browse an image from the computer</html>");

        jLabel_Image.setBackground(new java.awt.Color(204, 204, 204));
        jLabel_Image.setOpaque(true);
        jLabel_Image.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_ImageMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ProTypeHeadPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SeeImage_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(372, 372, 372)
                        .addComponent(jLabel3)
                        .addGap(4, 4, 4)
                        .addComponent(jButton_Browse, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(RomoveBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Addbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel_Image, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(ProTypeHeadPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_Browse))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE)))
                    .addComponent(jLabel_Image, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SeeImage_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RomoveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Addbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AddbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddbtnActionPerformed
        //Add image to the property
        //
        Property property = new Property();
        if(propertyId!=0){
        if(property.addImage(propertyId, property_image_path)){
            JOptionPane.showMessageDialog(null, "Image Added", "Add Image", 1);
        }
        else
            JOptionPane.showMessageDialog(null, "Image has not been Added","Add Image",2);
        }
        else{
            JOptionPane.showMessageDialog(null, "Select the property ","Add Image",2);
            
        }
        
    }//GEN-LAST:event_AddbtnActionPerformed

    private void RomoveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RomoveBtnActionPerformed
        // Remove the image
       try{
         String selectedItem = String.valueOf(jList1.getSelectedValue());
        Integer imageId = Integer.valueOf(selectedItem);
        int Yes_No = JOptionPane.showConfirmDialog(null, "Do you want to Delete this Image", "Delete Type", JOptionPane.YES_NO_OPTION);
        if(Yes_No ==JOptionPane.YES_OPTION){
        if(new Property().removeImage(imageId)){
            JOptionPane.showMessageDialog(null, "This Image has been deleted","Delete Type",1);
            jLabel_Image.setIcon(null);
        }
        else{
            JOptionPane.showMessageDialog(null, "Operation Failed","Delete Type",0);
        }
        }
           
       }
       catch(Exception ex){
           JOptionPane.showMessageDialog(null, "NO Image Selected","Error",0);
       }

        
        
        

    }//GEN-LAST:event_RomoveBtnActionPerformed

    private void SeeImage_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SeeImage_btnActionPerformed
        //see this property of images
        try{
        int rowIndex = jTable1.getSelectedRow();
        int id = Integer.valueOf(jTable1.getValueAt(rowIndex, 0).toString());
        ImageProperty_Window main = new ImageProperty_Window(id);
        main.setVisible(true);
        main.pack();
        main.setLocationRelativeTo(null);
        main.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(null, "Select Property","Error",2);
        }
        
        
        

       
    }//GEN-LAST:event_SeeImage_btnActionPerformed
public ImageIcon resizeImage(String path,byte[]byteImage){
    ImageIcon pic;
    if(byteImage !=null)pic = new ImageIcon(byteImage);
    else pic = new ImageIcon(path);
    Image img = pic.getImage().getScaledInstance(jLabel_Image.getWidth(), jLabel_Image.getHeight(), Image.SCALE_SMOOTH);
    ImageIcon image = new ImageIcon(img);
    return image;
    
}
    private void jButton_BrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_BrowseActionPerformed
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Select property Imaage");
        // C://Images is where my images are located in my local storage
        fileChooser.setCurrentDirectory(new File("C:\\Images"));
        //File Extension
        FileNameExtensionFilter fileFilter = new FileNameExtensionFilter("Images",".jpg",".png",".jpeg");
        fileChooser.addChoosableFileFilter(fileFilter);
        int fileState = fileChooser.showSaveDialog(null);
        if(fileState == JFileChooser.APPROVE_OPTION){
        String path = fileChooser.getSelectedFile().getAbsolutePath();
        jLabel_Image.setIcon(resizeImage(path,null));
        property_image_path = path;
        
    
    
}
        
        
        
    }//GEN-LAST:event_jButton_BrowseActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        int type = map.get(jComboBox1.getSelectedItem().toString());
         Property property = new Property();
        ArrayList<Property> list = property.PropertyListByType(type);
        //	Id. type square_feet ownerId price address bedrooms bathrooms age balcony pool backyard garage description
        //table columns
        String[] ColNames = {"ID", "Address"};
        Object[][] rows = new Object[list.size()][2];
        //add data form the list to the rows
        for (int i = 0; i < list.size(); i++) {
            rows[i][0] = list.get(i).getId();
            rows[i][1] = list.get(i).getAddress();
   
     

        }
        DefaultTableModel model = new DefaultTableModel(rows, ColNames);
        jTable1.setModel(model);
        
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
      //we should get the proeperty id
      int rowIndex = jTable1.getSelectedRow();
      propertyId = Integer.valueOf(jTable1.getValueAt(rowIndex, 0).toString());
      HashMap<byte[],Integer>imageList = new Property().PropertyImageList(propertyId);
      fillTypeList();
    }//GEN-LAST:event_jTable1MouseClicked

    private void jList1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList1MouseClicked
        // TODO add your handling code here:
        //Display all clicked images
        try{
        String selectedItem = String.valueOf(jList1.getSelectedValue());
        Integer imageId = Integer.valueOf(selectedItem);
        byte[]image = new Property().getImageById(imageId);
       jLabel_Image.setIcon(resizeImage("",image));
        }
        catch(Exception ex){
           
        }
       
        
    }//GEN-LAST:event_jList1MouseClicked

    private void jLabel_ImageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_ImageMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jLabel_ImageMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Images_Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Images_Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Images_Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Images_Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Images_Window().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Addbtn;
    private javax.swing.JPanel ProTypeHeadPanel;
    private javax.swing.JButton RomoveBtn;
    private javax.swing.JButton SeeImage_btn;
    private javax.swing.JButton jButton_Browse;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel_Image;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
