
import com.mysql.cj.xdevapi.Result;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Image;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

public class Login_page extends javax.swing.JFrame {

    public Login_page() {
        initComponents();
        ImageIcon icon = new ImageIcon("Image/Icon.png");
        //ImageIcon img =  new ImageIcon("Image/LoginImage.jpg");
        LabelB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/estate_icon.png")));
        UserNamelabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/user.png")));
        Passwordlabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/padlock.png")));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelB = new javax.swing.JPanel();
        LabelB = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        UserNamelabel = new javax.swing.JLabel();
        Passwordlabel = new javax.swing.JLabel();
        UserNameTField = new javax.swing.JTextField();
        PasswordField = new javax.swing.JPasswordField();
        LoginButton = new javax.swing.JButton();
        SignupButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 204));

        PanelB.setBackground(new java.awt.Color(204, 204, 204));
        PanelB.setForeground(new java.awt.Color(255, 255, 255));

        LabelB.setBackground(new java.awt.Color(51, 51, 0));
        LabelB.setForeground(new java.awt.Color(0, 0, 0));
        LabelB.setOpaque(true);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 153, 255));
        jLabel1.setText("Java Real Estate System");

        UserNamelabel.setBackground(new java.awt.Color(0, 51, 102));
        UserNamelabel.setOpaque(true);

        Passwordlabel.setBackground(new java.awt.Color(0, 51, 102));
        Passwordlabel.setOpaque(true);

        UserNameTField.setBackground(new java.awt.Color(255, 255, 255));
        UserNameTField.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        UserNameTField.setText("Username");
        UserNameTField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                UserNameTFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                UserNameTFieldFocusLost(evt);
            }
        });
        UserNameTField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserNameTFieldActionPerformed(evt);
            }
        });

        PasswordField.setBackground(new java.awt.Color(255, 255, 255));
        PasswordField.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        PasswordField.setText("jPasswordField1");
        PasswordField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                PasswordFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                PasswordFieldFocusLost(evt);
            }
        });
        PasswordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordFieldActionPerformed(evt);
            }
        });

        LoginButton.setBackground(new java.awt.Color(51, 102, 255));
        LoginButton.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        LoginButton.setText("Log In");
        LoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginButtonActionPerformed(evt);
            }
        });

        SignupButton1.setBackground(new java.awt.Color(51, 102, 255));
        SignupButton1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        SignupButton1.setText("Sign Up");
        SignupButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignupButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelBLayout = new javax.swing.GroupLayout(PanelB);
        PanelB.setLayout(PanelBLayout);
        PanelBLayout.setHorizontalGroup(
            PanelBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelBLayout.createSequentialGroup()
                .addComponent(LabelB, javax.swing.GroupLayout.PREFERRED_SIZE, 522, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(PanelBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelBLayout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(LoginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(SignupButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelBLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(PanelBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 468, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(PanelBLayout.createSequentialGroup()
                                .addGroup(PanelBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(UserNamelabel, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE)
                                    .addComponent(Passwordlabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(PanelBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(UserNameTField)
                                    .addComponent(PasswordField, javax.swing.GroupLayout.DEFAULT_SIZE, 231, Short.MAX_VALUE))))))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        PanelBLayout.setVerticalGroup(
            PanelBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelBLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(PanelBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelBLayout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addComponent(UserNamelabel, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelBLayout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addComponent(UserNameTField, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(PanelBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelBLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(Passwordlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelBLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(PasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(62, 62, 62)
                .addGroup(PanelBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LoginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SignupButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(PanelBLayout.createSequentialGroup()
                .addComponent(LabelB, javax.swing.GroupLayout.PREFERRED_SIZE, 611, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void UserNameTFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserNameTFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UserNameTFieldActionPerformed

    private void PasswordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PasswordFieldActionPerformed

    private void LoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginButtonActionPerformed
        // TODO add your handling code here:

        String username = UserNameTField.getText();
        String password = String.valueOf(PasswordField.getPassword());
        String query = "SELECT * FROM `signup1` WHERE `username`=? AND `password`=?";
        PreparedStatement Prstatement;
        ResultSet result;
        if (username.trim().toLowerCase().equals("username") || password.trim().toLowerCase().equals("password")) {
            JOptionPane.showMessageDialog(null, "Enter user Name");
        } else
            try {
            Prstatement = MyConnection.GetConnection().prepareStatement(query);
            Prstatement.setString(1, username);
            Prstatement.setString(2, password);
            result = Prstatement.executeQuery();
            if (result.next()) {
                Main_Window main = new Main_Window();
                main.setVisible(true);
                main.pack();
                main.setExtendedState(JFrame.MAXIMIZED_BOTH);
                //close the login window
                this.dispose();

            } else {
                JOptionPane.showMessageDialog(null, "invalid username or password");
            }

        } catch (SQLException ex) {
            Logger.getLogger(Login_page.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_LoginButtonActionPerformed

    private void SignupButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignupButton1ActionPerformed
        // TODO add your handling code here:
        Singup main = new Singup();
        main.setVisible(true);
        main.pack();
        main.setLocationRelativeTo(null);
        main.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        this.dispose();


    }//GEN-LAST:event_SignupButton1ActionPerformed

    private void UserNameTFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_UserNameTFieldFocusLost
        // TODO add your handling code here:
        //if the text field is emply set it into "Username"
        if (UserNameTField.getText().trim().equals("") || UserNameTField.getText().trim().toLowerCase().equals("username")) {
            UserNameTField.setText("Username");
            UserNameTField.setForeground(new Color(153, 153, 153));

        }
    }//GEN-LAST:event_UserNameTFieldFocusLost

    private void UserNameTFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_UserNameTFieldFocusGained
        // Remove the text if any text in the Textfield and when text field is Focus gained 
        if (UserNameTField.getText().trim().toLowerCase().equals("username")) {
            UserNameTField.setText(" ");
            UserNameTField.setForeground(Color.black);

        }


    }//GEN-LAST:event_UserNameTFieldFocusGained

    private void PasswordFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_PasswordFieldFocusGained
        // remove password from the password field
        String password;
        password = String.valueOf(PasswordField.getPassword());
        if (password.trim().toLowerCase().equals("password")) {
            PasswordField.setText("");
            PasswordField.setForeground(Color.black);
        }
    }//GEN-LAST:event_PasswordFieldFocusGained

    private void PasswordFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_PasswordFieldFocusLost
        // 
        String password;
        password = String.valueOf(PasswordField.getPassword());
        if (password.trim().equals("") || password.trim().toLowerCase().equals("password")) {
            PasswordField.setText("password");
            PasswordField.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_PasswordFieldFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login_page().setVisible(true);

            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelB;
    private javax.swing.JButton LoginButton;
    private javax.swing.JPanel PanelB;
    private javax.swing.JPasswordField PasswordField;
    private javax.swing.JLabel Passwordlabel;
    private javax.swing.JButton SignupButton1;
    private javax.swing.JTextField UserNameTField;
    private javax.swing.JLabel UserNamelabel;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
