
import java.awt.Color;
import javax.swing.BorderFactory;
import javax.swing.JFrame;
import javax.swing.border.Border;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author win
 */
public class Main_Window extends javax.swing.JFrame {

    /**
     * Creates new form Main_Window
     */
    public Main_Window() {
        initComponents();
        Border menu_items = BorderFactory.createMatteBorder(0, 0, 1, 0, Color.white);
        HomeLabel.setBorder(menu_items);
        ProperLabel.setBorder(menu_items);
        ProTypeLabel.setBorder(menu_items);
        ProImageLabel.setBorder(menu_items);
        OwnerLabel.setBorder(menu_items);
        ClientLabel.setBorder(menu_items);
        SalesLabel1.setBorder(menu_items);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        HomeLabel = new javax.swing.JLabel();
        ProperLabel = new javax.swing.JLabel();
        ProTypeLabel = new javax.swing.JLabel();
        ProImageLabel = new javax.swing.JLabel();
        OwnerLabel = new javax.swing.JLabel();
        ClientLabel = new javax.swing.JLabel();
        SalesLabel1 = new javax.swing.JLabel();
        HomeLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setForeground(new java.awt.Color(0, 0, 0));

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setForeground(new java.awt.Color(153, 153, 153));

        HomeLabel.setBackground(new java.awt.Color(255, 153, 51));
        HomeLabel.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        HomeLabel.setForeground(new java.awt.Color(255, 255, 255));
        HomeLabel.setText("  My APP");
        HomeLabel.setOpaque(true);

        ProperLabel.setBackground(new java.awt.Color(51, 51, 51));
        ProperLabel.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        ProperLabel.setForeground(new java.awt.Color(255, 255, 255));
        ProperLabel.setText("Property");
        ProperLabel.setOpaque(true);
        ProperLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ProperLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ProperLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ProperLabelMouseExited(evt);
            }
        });

        ProTypeLabel.setBackground(new java.awt.Color(51, 51, 51));
        ProTypeLabel.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        ProTypeLabel.setForeground(new java.awt.Color(255, 255, 255));
        ProTypeLabel.setText("Property-Type");
        ProTypeLabel.setOpaque(true);
        ProTypeLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ProTypeLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ProTypeLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ProTypeLabelMouseExited(evt);
            }
        });

        ProImageLabel.setBackground(new java.awt.Color(51, 51, 51));
        ProImageLabel.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        ProImageLabel.setForeground(new java.awt.Color(255, 255, 255));
        ProImageLabel.setText("Property-Images");
        ProImageLabel.setOpaque(true);
        ProImageLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ProImageLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ProImageLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ProImageLabelMouseExited(evt);
            }
        });

        OwnerLabel.setBackground(new java.awt.Color(51, 51, 51));
        OwnerLabel.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        OwnerLabel.setForeground(new java.awt.Color(255, 255, 255));
        OwnerLabel.setText("Owner");
        OwnerLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                OwnerLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                OwnerLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                OwnerLabelMouseExited(evt);
            }
        });

        ClientLabel.setBackground(new java.awt.Color(51, 51, 51));
        ClientLabel.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        ClientLabel.setForeground(new java.awt.Color(255, 255, 255));
        ClientLabel.setText("Client");
        ClientLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ClientLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ClientLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ClientLabelMouseExited(evt);
            }
        });

        SalesLabel1.setBackground(new java.awt.Color(51, 51, 51));
        SalesLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        SalesLabel1.setForeground(new java.awt.Color(255, 255, 255));
        SalesLabel1.setText("Sales");
        SalesLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SalesLabel1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SalesLabel1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SalesLabel1MouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ProperLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ProTypeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ProImageLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(OwnerLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ClientLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(SalesLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addComponent(HomeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 282, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(HomeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ProperLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ProTypeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ProImageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(OwnerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ClientLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(SalesLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 230, Short.MAX_VALUE))
        );

        HomeLabel1.setBackground(new java.awt.Color(255, 153, 51));
        HomeLabel1.setFont(new java.awt.Font("Arial Black", 1, 48)); // NOI18N
        HomeLabel1.setForeground(new java.awt.Color(0, 153, 51));
        HomeLabel1.setText("Java Based Real Estate ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(HomeLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(HomeLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ProperLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProperLabelMouseEntered

        ProperLabel.setBackground(Color.white);
        ProperLabel.setForeground(new Color(153, 153, 153));
    }//GEN-LAST:event_ProperLabelMouseEntered

    private void ProperLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProperLabelMouseExited

        ProperLabel.setBackground(new Color(51, 51, 51));
        ProperLabel.setForeground(Color.white);
    }//GEN-LAST:event_ProperLabelMouseExited

    private void ProTypeLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProTypeLabelMouseEntered
        ProTypeLabel.setBackground(Color.white);
        ProTypeLabel.setForeground(new Color(153, 153, 153));

    }//GEN-LAST:event_ProTypeLabelMouseEntered

    private void ProTypeLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProTypeLabelMouseExited
        ProTypeLabel.setBackground(new Color(51, 51, 51));
        ProTypeLabel.setForeground(Color.white);
    }//GEN-LAST:event_ProTypeLabelMouseExited

    private void ProImageLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProImageLabelMouseEntered
        ProImageLabel.setBackground(Color.white);
        ProImageLabel.setForeground(new Color(153, 153, 153));
    }//GEN-LAST:event_ProImageLabelMouseEntered

    private void ProImageLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProImageLabelMouseExited
        ProImageLabel.setBackground(new Color(51, 51, 51));
        ProImageLabel.setForeground(Color.white);
    }//GEN-LAST:event_ProImageLabelMouseExited

    private void OwnerLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OwnerLabelMouseEntered
        OwnerLabel.setBackground(Color.white);
        OwnerLabel.setForeground(new Color(153, 153, 153));
    }//GEN-LAST:event_OwnerLabelMouseEntered

    private void OwnerLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OwnerLabelMouseExited
        OwnerLabel.setBackground(new Color(51, 51, 51));
        OwnerLabel.setForeground(Color.white);
    }//GEN-LAST:event_OwnerLabelMouseExited

    private void ClientLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ClientLabelMouseEntered
        ClientLabel.setBackground(Color.white);
        ClientLabel.setForeground(new Color(153, 153, 153));
    }//GEN-LAST:event_ClientLabelMouseEntered

    private void ClientLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ClientLabelMouseExited
        ClientLabel.setBackground(new Color(51, 51, 51));
        ClientLabel.setForeground(Color.white);
    }//GEN-LAST:event_ClientLabelMouseExited

    private void ProTypeLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProTypeLabelMouseClicked
        // TODO add your handling code here:
        //open propertype window
        Property_Type_Window main = new Property_Type_Window();
        main.setVisible(true);
        main.pack();
        main.setLocationRelativeTo(null);
        main.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

        //main.setExtendedState(JFrame.MAXIMIZED_BOTH);
        //close the login window
        //this.dispose();
    }//GEN-LAST:event_ProTypeLabelMouseClicked

    private void OwnerLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OwnerLabelMouseClicked
        // TODO add your handling code here:
        Owner_Window main = new Owner_Window();
        main.setVisible(true);
        main.pack();
        main.setLocationRelativeTo(null);
        main.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_OwnerLabelMouseClicked

    private void ClientLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ClientLabelMouseClicked
        // TODO add your handling code here:
        Client_Window main = new Client_Window();
        main.setVisible(true);
        main.pack();
        main.setLocationRelativeTo(null);
        main.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_ClientLabelMouseClicked

    private void ProperLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProperLabelMouseClicked
        // TODO add your handling code here:
        Property_Window main = new Property_Window();
        main.setVisible(true);
        main.pack();
        main.setLocationRelativeTo(null);
        main.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        
    }//GEN-LAST:event_ProperLabelMouseClicked

    private void ProImageLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProImageLabelMouseClicked
        // TODO add your handling code here:
        Images_Window main = new Images_Window();
        main.setVisible(true);
        main.pack();
        main.setLocationRelativeTo(null);
        main.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        
    }//GEN-LAST:event_ProImageLabelMouseClicked

    private void SalesLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SalesLabel1MouseClicked
        // TODO add your handling code here:
        Sale_Window main = new Sale_Window();
        main.setVisible(true);
        main.pack();
        main.setLocationRelativeTo(null);
        main.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_SalesLabel1MouseClicked

    private void SalesLabel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SalesLabel1MouseEntered
        // TODO add your handling code here:
        SalesLabel1.setBackground(Color.white);
        SalesLabel1.setForeground(new Color(153, 153, 153));
    }//GEN-LAST:event_SalesLabel1MouseEntered

    private void SalesLabel1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SalesLabel1MouseExited
        // TODO add your handling code here:
         SalesLabel1.setBackground(new Color(51, 51, 51));
        SalesLabel1.setForeground(Color.white);
    }//GEN-LAST:event_SalesLabel1MouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main_Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main_Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main_Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main_Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new Main_Window().setExtendedState(JFrame.MAXIMIZED_BOTH);
                new Main_Window().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ClientLabel;
    private javax.swing.JLabel HomeLabel;
    private javax.swing.JLabel HomeLabel1;
    private javax.swing.JLabel OwnerLabel;
    private javax.swing.JLabel ProImageLabel;
    private javax.swing.JLabel ProTypeLabel;
    private javax.swing.JLabel ProperLabel;
    private javax.swing.JLabel SalesLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
